TRPO-Lab5.Web/Models/ContainerViewModel.cs
using TRPO_Lab3.Lib.TRPO_Lab3.Lib;

public class ContainerViewModel
{
    public double P1 { get; set; } // Периметр нижнего основания
    public double P2 { get; set; } // Периметр верхнего основания
    public double H { get; set; }  // Апофема (высота боковой грани)

    public double Result => SurfaceArea.TruncatedPyramidLateralSurfaceArea(P1, P2, H);
}

TRPO-Lab5.Web/Models/ErrorViewModel.cs
namespace TRPO_Lab5.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TRPO-Lab5.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TRPO_Lab5.Web.Models;

namespace TRPO_Lab5.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TRPO-Lab5.Web/Controllers/SurfaceAreaController.cs
using Microsoft.AspNetCore.Mvc;
using TRPO_Lab3.Lib;
using TRPO_Lab5.Web.Models;

public class SurfaceAreaController : Controller
{
    [HttpGet]
    public ActionResult Index(ContainerViewModel vm)
    {
        return View(vm);
    }

    [HttpPost]
    public ActionResult Index(ContainerViewModel vm, IFormCollection collection)
    {
        try
        {
            double P1 = vm.P1;
            double P2 = vm.P2;
            double H = vm.H;
            double result = vm.Result;
            return View(vm);
        }
        catch (Exception ex)
        {
            return View("Error", new ErrorViewModel { RequestId = ex.Message });
        }
    }
}

TRPO-Lab5.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TRPO-Lab5.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TRPO_Lab5.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TRPO_Lab5.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TRPO_Lab5.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SurfaceArea" asp-action="Index">Calc</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TRPO_Lab5.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TRPO-Lab5.Web/Views/SurfaceArea/Index.cshtml
@{
    ViewData["Title"] = "SurfaceArea";
}

<head>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>

<div class="text-center">
    <h1 align="left" class="display-10">Расчет боковой поверхности правильной усеченной пирамиды</h1>
    <p></p>
    <p align="left">Разработал: Морозов Семен Андреевич</p>
    <p align="left">Студент гр. НМТ-223901</p>
    <div class="text-center">
        <img src="/image/TruncatedPyramid.png" style="position: relative; width: 25%">
        <p></p>
        <img src="/image/TruncatedPyramidFormula.png" style="position: relative; width: 10%">
    </div>
</div>

@model ContainerViewModel

@using (Html.BeginForm())
{
        <div class="form-group">
            <p>
                <label for="P1" class="col-sm-1">Периметр нижнего основания (P1):</label>
                <input type="text" name="P1" id="P1" value="@Model.P1" class="form-control" />
            </p>
            <p>
                <label for="P2" class="col-sm-1">Периметр верхнего основания (P2):</label>
                <input type="text" name="P2" id="P2" value="@Model.P2" class="form-control" />
            </p>
            <p>
                <label for="H" class="col-sm-1">Апофема (H):</label>
                <input type="text" name="H" id="H" value="@Model.H" class="form-control" />
            </p>
        </div>
        <p>
        @if (@Model.Result != -1)
        {
                    <p>Площадь: @Model.Result</p>
        }
        else
        {
                    <p class="text-danger">Введите положительные значения для периметров и апофемы!</p>
        }
        </p>
        <p>
            <input type="submit" value="Вычислить" class="btn btn-primary" />
        </p>
}